/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../public/models/umbrella.glb 
*/

import React from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { useCustomization } from "../contexts/Customization";
import useFabricTextures from "../hooks/useFabricTextures";
import useSteelTextures from "../hooks/useSteelTextures";
import usePlasticTextures from "../hooks/usePlasticTextures";

export function Umbrella(props) {
	const { nodes, materials } = useGLTF("models/umbrella.glb");
	const { packageType, umbrellaShape, fabricColor, steelColor } =
		useCustomization();

	const fabricTextureProps = useFabricTextures();
	const steelTextureProps = useSteelTextures();
	const plasticTextureProps = usePlasticTextures();

	return (
		<group {...props} dispose={null}>
			{/* Canopy */}
			<mesh
				visible={umbrellaShape.name === "Square"}
				geometry={nodes.Square_Canopy.geometry}
				// material={materials.Material}
				position={[0, 3.435, 0]}
			>
				<meshStandardMaterial
					side={THREE.DoubleSide}
					{...fabricTextureProps}
					color={fabricColor.color}
				/>
			</mesh>
			<mesh
				visible={umbrellaShape.name === "Rectangle"}
				geometry={nodes.Rectangular_Canopy.geometry}
				// material={materials["Material.001"]}
				position={[0, 3.472, 0]}
			>
				<meshStandardMaterial
					side={THREE.DoubleSide}
					{...fabricTextureProps}
					color={fabricColor.color}
				/>
			</mesh>
			<mesh
				visible={umbrellaShape.name === "Truncated Square"}
				geometry={nodes.Truncated_Canopy.geometry}
				// material={materials["Material.005"]}
				position={[0, 2.36, 0]}
				scale={[0.115, 1, 0.115]}
			>
				<meshStandardMaterial
					side={THREE.DoubleSide}
					{...fabricTextureProps}
					color={fabricColor.color}
				/>
			</mesh>

			{/* Gutter */}
			<mesh
				visible={
					umbrellaShape.name === "Square" &&
					packageType.name !== "Package A"
				}
				geometry={nodes.Square_Gutter.geometry}
				// material={materials.Material}
				position={[0, 2.383, 0]}
				rotation={[0, Math.PI / 2, 0]}
				scale={[0.685, 1, 1]}
			>
				<meshStandardMaterial
					side={THREE.DoubleSide}
					{...steelTextureProps}
					color={steelColor.color}
				/>
			</mesh>
			<mesh
				visible={
					umbrellaShape.name === "Rectangle" &&
					packageType.name !== "Package A"
				}
				geometry={nodes.Rectangular_Gutter.geometry}
				// material={materials.Material}
				position={[-2.337, 3.429, -1.6]}
			>
				<meshStandardMaterial
					side={THREE.DoubleSide}
					{...steelTextureProps}
					color={steelColor.color}
				/>
			</mesh>
			<mesh
				visible={
					umbrellaShape.name === "Truncated Square" &&
					packageType.name !== "Package A"
				}
				geometry={nodes.Truncated_GUTTER.geometry}
				// material={materials.Material}
				scale={2.298}
			>
				<meshStandardMaterial
					side={THREE.DoubleSide}
					{...steelTextureProps}
					color={steelColor.color}
				/>
			</mesh>

			{/* Center Post */}
			<mesh
				visible={umbrellaShape.name === "Square"}
				geometry={nodes.Square_Center_Post.geometry}
				// material={materials.Material}
				rotation={[-0.172, 1.571, 0]}
			>
				<meshStandardMaterial
					{...steelTextureProps}
					color={steelColor.color}
				/>
			</mesh>
			<mesh
				visible={umbrellaShape.name === "Truncated Square"}
				geometry={nodes.Truncated_Center_Post.geometry}
				// material={materials.Material}
				rotation={[0, Math.PI / 4, -0.172]}
			>
				<meshStandardMaterial
					{...steelTextureProps}
					color={steelColor.color}
				/>
			</mesh>
			<mesh
				visible={umbrellaShape.name === "Rectangle"}
				geometry={nodes.Rectangular_Center_Post.geometry}
				// material={materials.Material}
				rotation={[0, 0, -0.172]}
			>
				<meshStandardMaterial
					{...steelTextureProps}
					color={steelColor.color}
				/>
			</mesh>

			{/* Frame */}
			<mesh
				visible={umbrellaShape.name === "Square"}
				geometry={nodes.Square_Frame.geometry}
				// material={materials.Material}
				position={[-0.003, 0, -0.003]}
				rotation={[-Math.PI, 1.385, 2.969]}
			>
				<meshStandardMaterial
					side={THREE.DoubleSide}
					{...steelTextureProps}
					color={steelColor.color}
				/>
			</mesh>
			<mesh
				visible={umbrellaShape.name === "Rectangle"}
				geometry={nodes.Rectangular_Frame.geometry}
				// material={materials.Material}
				position={[1.363, 2.548, 0]}
				rotation={[0, 0, -0.172]}
			>
				<meshStandardMaterial
					side={THREE.DoubleSide}
					{...steelTextureProps}
					color={steelColor.color}
				/>
			</mesh>
			<mesh
				visible={umbrellaShape.name === "Truncated Square"}
				geometry={nodes.Truncated_Frame.geometry}
				// material={materials.Material}
				position={[0, 0, -0.004]}
				rotation={[0, 0.971, -0.172]}
			>
				<meshStandardMaterial
					side={THREE.DoubleSide}
					{...steelTextureProps}
					color={steelColor.color}
				/>
			</mesh>

			{/* Wind Columns */}
			<mesh
				visible={
					umbrellaShape.name === "Square" &&
					packageType.name !== "Package A"
				}
				geometry={nodes.Square_Columns.geometry}
				// material={materials.Material}
				position={[0, 1.18, 0]}
				rotation={[0, Math.PI / 2, 0]}
				scale={[0.684, 1, 1.001]}
			>
				<meshStandardMaterial
					side={THREE.DoubleSide}
					{...steelTextureProps}
					color={steelColor.color}
				/>
			</mesh>
			<mesh
				visible={
					umbrellaShape.name === "Rectangle" &&
					packageType.name !== "Package A"
				}
				geometry={nodes.Rectangular_Columns.geometry}
				// material={materials.Material}
				position={[2.373, 2.36, 1.614]}
			>
				<meshStandardMaterial
					side={THREE.DoubleSide}
					{...steelTextureProps}
					color={steelColor.color}
				/>
			</mesh>
			<mesh
				visible={
					umbrellaShape.name === "Truncated Square" &&
					packageType.name !== "Package A"
				}
				geometry={nodes.Truncated_Columns.geometry}
				// material={materials.Material}
				position={[0, 1.18, 0]}
				rotation={[0, Math.PI / 4, 0]}
				scale={[0.684, 1, 1.001]}
			>
				<meshStandardMaterial
					side={THREE.DoubleSide}
					{...steelTextureProps}
					color={steelColor.color}
				/>
			</mesh>

			{/* Cover */}
			<mesh
				visible={
					umbrellaShape.name === "Square" &&
					packageType.name === "Package C"
				}
				geometry={nodes.Square_Cover.geometry}
				// material={materials.Material}
			>
				<meshStandardMaterial
					side={THREE.DoubleSide}
					{...plasticTextureProps}
					color={"#DCF0EF"}
					transparent
					opacity={0.25}
				/>
			</mesh>
			<mesh
				visible={
					umbrellaShape.name === "Rectangle" &&
					packageType.name === "Package C"
				}
				geometry={nodes.Rectangular_Cover.geometry}
				// material={materials.Material}
			>
				<meshStandardMaterial
					side={THREE.DoubleSide}
					{...plasticTextureProps}
					color={"#DCF0EF"}
					transparent
					opacity={0.25}
				/>
			</mesh>
			<mesh
				visible={
					umbrellaShape.name === "Truncated Square" &&
					packageType.name === "Package C"
				}
				geometry={nodes.Truncated_Cover.geometry}
				// material={materials.Material}
				position={[-1, 0, 3.408]}
			>
				<meshStandardMaterial
					side={THREE.DoubleSide}
					{...plasticTextureProps}
					color={"#DCF0EF"}
					transparent
					opacity={0.25}
				/>
			</mesh>

			{/* Heater */}
			<mesh
				visible={umbrellaShape.name === "Square"}
				geometry={nodes.Square_Heater.geometry}
				// material={nodes.Square_Heater.material}
				rotation={[0, 1.412, -0.172]}
			/>
			<mesh
				visible={umbrellaShape.name === "Rectangle"}
				geometry={nodes.Rectangular_Heater.geometry}
				// material={nodes.Rectangular_Heater.material}
				rotation={[0, -1.195, -0.172]}
			/>
			<mesh
				visible={umbrellaShape.name === "Truncated Square"}
				geometry={nodes.Truncated_Heater.geometry}
				// material={nodes.Truncated_Heater.material}
				rotation={[0, 0.627, -0.172]}
			/>
		</group>
	);
}

useGLTF.preload("models/umbrella.glb");
