/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../public/models/umbrella/scene.gltf 
Author: k3v1nc0 (https://sketchfab.com/k3v1nc0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/floating-parasol-sunshade-patio-umbrella-280a65bca20b425e96617b0dd78cce21
Title: Floating Parasol Sunshade Patio Umbrella
*/

import React from "react";
import * as THREE from "three";
import { useGLTF, useTexture } from "@react-three/drei";
import { useCustomization } from "../contexts/Customization";

export function Umbrella(props) {
	const { umbrellaShape, fabricColor, steelColor } = useCustomization();
	const { nodes, materials } = useGLTF("models/umbrella/scene.gltf");

	const fabricTextureProps = useTexture({
		normalMap: "public/textures/fabric/Fabric_polyester_001_normal.jpg",
		roughnessMap:
			"public/textures/fabric/Fabric_polyester_001_roughness.jpg",
		heightMap: "public/textures/fabric/Fabric_polyester_001_height.png",
		aoMap: "public/textures/fabric/Fabric_polyester_001_ambientOcclusion.jpg",
	});

	const steelTextureProps = useTexture({
		normalMap: "public/textures/steel/Metal_Steel_Brushed_001_normal.jpg",
		roughnessMap:
			"public/textures/steel/Metal_Steel_Brushed_001_roughness.jpg",
		heightMap: "public/textures/steel/Metal_Steel_Brushed_001_height.png",
		aoMap: "public/textures/steel/Metal_Steel_Brushed_001_ambientOcclusion.jpg",
		metalnessMap:
			"public/textures/steel/Metal_Steel_Brushed_001_metallic.jpg",
		diffuseMap: "public/textures/steel/Metal_Steel_Brushed_001_diffuse.jpg",
	});

	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={0.808}>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
						<mesh
							geometry={nodes.Parasol_Parasol_frame_0.geometry}
							// material={materials.Parasol_frame}
						>
							<meshStandardMaterial
								{...steelTextureProps}
								color={steelColor.color}
							/>
						</mesh>
						<mesh
							geometry={nodes.Parasol_Parasol_fabric_0.geometry}
							// material={materials.Parasol_fabric}
						>
							<meshStandardMaterial
								{...fabricTextureProps}
								color={fabricColor.color}
							/>
						</mesh>
						<mesh
							geometry={nodes.Parasol_Parasol_stone_0.geometry}
							material={materials.Parasol_stone}
						></mesh>
						<mesh
							geometry={nodes.Parasol_Parasol_metaal_0.geometry}
							material={materials.Parasol_metaal}
						></mesh>
						<mesh
							geometry={nodes.Parasol_Parasol_wheels_0.geometry}
							material={materials.Parasol_wheels}
						></mesh>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("models/umbrella/scene.gltf");
